name = "PrunedFFT"
authors = ["Andr√© Ferrari <andferrari@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
PrunedFFTExt = "CUDA"
